version: "3.8"

services:
  search_db:
    image: mariadb:10.6.3
    container_name: search_db
    environment:
      - MARIADB_ALLOW_EMPTY_ROOT_PASSWORD=True
    env_file:
      - .env
    restart: on-failure
    ports:
      - "3301:3306"
    volumes:
      - db_data:/var/lib/mysql`
    networks:
      - separated_network
volumes:
  db_data:
  manticore_data:

networks:
  separated_network: